config/routes.rb
IdeaThread::Application.routes.draw do
  resources :ideas do
    member do
      get 'vote'
    end
  end

  devise_for :users

  get "home/index"

  root :to => "ideas#index"

  namespace :api do
	  namespace :v1  do
	    resources :tokens,:only => [:create, :destroy]
	  end
	end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :addtional_info, :description, :title,  :documents_attributes

  validates :title, :description, :presence => true

  belongs_to :user, :foreign_key => :created_by

  #TODO - If required will implement counter_cache for performance
  has_many :votes

  acts_as_commentable

  has_paper_trail

  has_many :documents, :as => :attachable

  accepts_nested_attributes_for :documents, :allow_destroy => true

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])
    @idea.created_by = current_user.id

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])
    @idea.updated_by = current_user.id

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  def vote 
    @idea = Idea.find(params[:id])
    @vote = Vote.new
    @vote.user = current_user
    @vote.idea = @idea

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @idea, notice: 'You voted successfully.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { redirect_to @idea, alert: @vote.errors.full_messages }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea, :html => {:class => 'form-horizontal', :multipart => true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, :input_html => { :cols => 50, :rows => 5 } %>
    <%= f.input :addtional_info, :input_html => { :cols => 50, :rows => 5 } %>

    
    <div class="control-group text optional">
      <label class="text optional control-label" for="idea_addtional_info">Attachments</label>
      
      <div class="controls" id="upload_box" >
        <input name="idea[documents_attributes][][data]" type="file">
      </div>

      <div class="controls">
        <%= link_to "Attach more", "#", :id => "attach_more" %>
      </div>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table class="table table-striped">
  <thead>
    <tr>
    <th><th>
    <th><th>
    <th><th>
    <th><th>

  </tr>
  </thead>
  <tbody>
<% @ideas.each do |idea| %>
  <tr>
    <td>
      <div class="votes">
        <div class="mini-counts"><%= idea.votes.count %></div>
        <div>votes</div>
      </div>
    </td>

    <td>
      <div class="status commented">
        <div class="mini-counts"><%= idea.votes.count %></div>
        <div>Comment</div>
      </div>
    </td>

    <td>
      <div class="views">
        <div class="mini-counts"><%= idea.votes.count %></div>
        <div>views</div>
      </div>
    </td>

    <td>
      <div class="summary">
        <h3><%= link_to idea.title, idea %></h3>
        <div class="started">
          <span class="relativetime" title="2012-05-21 05:45:24Z"><%= time_ago_in_words(idea.created_at) %></span>
          <a href="/users/666596/rasman"><%= idea.user.name%></a>
        </div>
      <div>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= button_to 'New Idea', new_idea_path , :method => "get", :class => "btn btn-primary f-left" %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span1">

      <div class="votes">
        <div class="mini-counts"><%= @idea.votes.count %></div>
        <div>votes</div>
      <%= button_to 'Vote', vote_idea_path(@idea), :method => "get", :class => "btn btn-success" %>
      </div>
  </div>
  <div class="span11">
    <p>
      <b>Title:</b>
      <%= @idea.title %>
    </p>

    <p>
      <b>Description:</b>
      <%= @idea.description %>
    </p>

    <p>
      <b>Addtional info:</b>
      <%= @idea.addtional_info %>
    </p>


    <%= link_to 'Edit', edit_idea_path(@idea) %> |
    <%= link_to 'Back', ideas_path %>

  </div>
</div>